### ISSUE TITLE
failed to emit precompiled header '/Users/itsec/Library/Developer/Xcode/DerivedData/ReadyToUseUIDemo-bvjzxyihmsqumnbrtbgzxusmfvjk/Build/Intermediates.noindex/PrecompiledHeaders/ReadyToUseUIDemo-Bridging-Header-swift_2M99E56UDZCRZ-clang_3850661X1N6LD.pch' for bridging header '/Users/itsec/Downloads/scanbot-sdk-example-ios-master 2/ReadyToUseUIDemo/ReadyToUseUIDemo-Bridging-Header.h

### ISSUE THREAD

**Issue by Daniyal073** [doo/scanbot-sdk-example-ios#10]

**Comment by eddyfrank** [comment]
See https://github.com/doo/scanbot-sdk-example-ios/issues/9

**Comment by smyrnovbohdan1-eng** [comment]
## Xcode Compatibility Enhancement: @retroactive Attribute Implementation

### Description
While working with the SwiftUIComponentsExample project, I noticed that builds on Xcode 15.4 and 15.1 encounter an issue with the `@retroactive` attribute. I'd like to share my findings and suggest a potential solution that might help other developers.

### Current Behavior
- ❌ Xcode 15.1: Build fails due to unrecognized `@retroactive` attribute
- ❌ Xcode 15.4: Same behavior as 15.1
- ✅ Xcode 16.0: Works as expected

### Technical Details
The compiler doesn't recognize the `@retroactive` attribute when implementing `Identifiable` conformance for `SBSDKScannedPage` in Xcode versions prior to 16.0.

### Suggested Solution
I found that implementing a conditional compilation block resolves this issue while maintaining compatibility across Xcode versions
 ```swift
#if hasFeature(RetroactiveAttribute)
extension SBSDKScannedPage: @retroactive Identifiable { }
#else
extension SBSDKScannedPage: Identifiable { }
#endif
 ```

### Benefits
This enhancement would help developers who are using various Xcode versions to work with the SDK more smoothly, especially those who haven't upgraded to Xcode 16.0 yet.

I hope this suggestion is helpful. Please let me know if you need any additional information or clarification.
